[package]
name = "nucleotide-env"
version = "0.1.0"
edition = "2021"
description = "Shell environment management for Nucleotide editor"
license = "MPL-2.0"
repository = "https://github.com/mralexgray/nucleotide"

[dependencies]
nucleotide-logging.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time", "process"] }
anyhow.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3.0"