[package]
name = "nucleotide"
edition = "2021"
authors = ["Iain H. <iain@spiralpoint.org>", "Alexander Polakov <alex@plhk.dev>", "Blaž Hrastnik <blaz@mxxn.io>"]
description = "A native GUI for the Helix editor"
include = ["src/**/*", "README.md"]
default-run = "nucl"
version = "0.1.0"
license = "MPL-2.0"

[features]
default = ["git"]
unicode-lines = ["helix-core/unicode-lines"]
integration = ["helix-event/integration_test"]
git = ["helix-vcs/git"]

[[bin]]
name = "nucl"
path = "src/main.rs"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "faa45c53d7754cfdd91d2f7edd3c786abc703ec7" }
sum_tree = { git = "https://github.com/zed-industries/zed", rev = "faa45c53d7754cfdd91d2f7edd3c786abc703ec7" }

helix-stdx = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }
helix-core = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }
helix-event = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }
helix-view = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }
helix-lsp = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }
helix-vcs = { git = "https://github.com/helix-editor/helix", tag = "25.07.1", features = ["git"] }
helix-loader = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }
helix-term = { git = "https://github.com/helix-editor/helix", tag = "25.07.1" }

# Dependencies used by extracted code
anyhow = "1.0"
arc-swap = "1.7"
ctor = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures-util = "0.3"
unicode-segmentation = "1.10"
smallvec = "1.13"
fern = "0.6"

chrono = { version = "0.4", default-features = false, features = ["clock"] }
log = "0.4"
once_cell = "1.19"

# File picker
nucleo = "0.2"
ignore = "0.4"
# markdown doc rendering
pulldown-cmark = { version = "0.10", default-features = false }
# file type detection
content_inspector = "0.2.4"
# file system watching
notify = "6.1"
# embed assets
rust-embed = "8.5"

# opening URLs
open = "5.1.2"
url = "2.5.4"

# config
toml = "0.8"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# ripgrep for global search
grep-regex = "0.1.12"
grep-searcher = "0.1.13"

# Unicode handling
unicode-width = "0.1"

[dev-dependencies]
tempfile = "3.8"

[package.metadata.bundle]
name = "Nucleotide"
identifier = "org.spiralpoint.nucleotide"
icon = ["assets/nucleotide.icns"]
version = "0.1.0"
copyright = "Copyright © 2025 Iain H. All rights reserved."
category = "public.app-category.developer-tools"
short_description = "A native GUI for the Helix editor"
long_description = """
Nucleotide is a native GUI implementation of the Helix text editor,
built with GPUI (the UI framework from Zed editor). It brings modal
editing to a native GUI application.
"""

