#!/bin/bash
echo "Starting Nucleotide with search navigation logging..."
echo "Instructions:"
echo "1. Press '/' to open search"
echo "2. Type 'test' and press Enter"  
echo "3. Press 'n' to go to next match"
echo "4. Check if cursor moves to next 'test' occurrence"
echo ""
echo "Logs will show below:"
echo "================================"
RUST_LOG=info ./target/release/nucl test_search.txt 2>&1 | grep -E "'n'|search|Search|Compositor|View"