[package]
name = "nucleotide-workspace"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
description = "Workspace management for Nucleotide editor (Layer 5)"
categories = ["text-editors", "gui"]
rust-version = "1.88"

[dependencies]
nucleotide-core = { path = "../nucleotide-core" }
nucleotide-events = { path = "../nucleotide-events" }

# GPUI
gpui = { workspace = true }

# Helix dependencies
helix-view = { workspace = true }

# Standard dependencies
nucleotide-logging = { workspace = true }
