# Nucleotide Ocean Theme - A WCAG-compliant cool-toned theme
# Background: Cadet Gray (#A3BAC3) with cerulean and moonstone accents

attribute = "cerulean-dark"
keyword = "moonstone-dark"
"keyword.directive" = "cerulean-dark" # -- preprocessor comments (#if in C)
namespace = "cerulean-dark"
punctuation = "ink"
"punctuation.delimiter" = "ink"
operator = "cerulean-dark"
special = "moonstone-dark"
"variable.other.member" = "midnight"
variable = "ink"
# variable = "moonstone-dark" # TODO: metavariables only
# "variable.parameter" = { fg = "ink", modifiers = ["underlined"] }
"variable.parameter" = { fg = "ink" }
"variable.builtin" = "ocean-deep"
type = "midnight"
"type.builtin" = "midnight" # TODO: distinguish?
constructor = "cerulean-dark"
function = "midnight"
"function.macro" = "cerulean-dark"
"function.builtin" = "midnight"
tag = "moonstone-dark"
comment = "steel"
constant = "midnight"
"constant.builtin" = "midnight"
string = "ocean-deep"
"constant.numeric" = "moonstone-dark"
"constant.character.escape" = "moonstone-dark"
# used for lifetimes
label = "moonstone-dark"
tabstop = { modifiers = ["italic"], bg = "mist" }

"markup.heading" = "cerulean-dark"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "ocean-deep", modifiers = ["underlined"] }
"markup.link.text" = "moonstone-dark"
"markup.raw" = "moonstone-dark"

"diff.plus" = "#047857"
"diff.minus" = "#991b1b"
"diff.delta" = "#005577"

# TODO: differentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "cadet-gray" }
"ui.background.separator" = { fg = "smoke" }
"ui.linenr" = { fg = "smoke" }
"ui.linenr.selected" = { fg = "cerulean-dark" }
"ui.statusline" = { fg = "ink", bg = "cadet-gray" }
"ui.statusline.inactive" = { fg = "steel", bg = "cadet-gray" }
"ui.popup" = { bg = "mist" }
"ui.window" = { fg = "smoke" }
"ui.help" = { bg = "#005577", fg = "#ffffff" }
"ui.text" = { fg = "ink" }
"ui.text.focus" = { fg = "midnight" }
"ui.text.inactive" = "steel"
"ui.text.directory" = { fg = "cerulean-dark" }
"ui.virtual" = { fg = "smoke" }
"ui.virtual.ruler" = { bg = "mist" }
"ui.virtual.jump-label" = { fg = "#991b1b", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "smoke" }

"ui.selection" = { bg = "#00709066" }
"ui.selection.primary" = { bg = "#00709066" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "cerulean-light" }
"ui.cursor.insert" = { bg = "midnight" }
"ui.cursor.primary.select" = { bg = "cerulean-light" }
"ui.cursor.primary.insert" = { bg = "midnight" }
"ui.cursor.match" = { fg = "#ffffff", bg = "#005577" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "mist" }
"ui.highlight" = { bg = "mist" }
"ui.highlight.frameline" = { bg = "#91a8b1" }
"ui.debug" = { fg = "#005577" }
"ui.debug.breakpoint" = { fg = "#991b1b" }
"ui.menu" = { fg = "ink", bg = "mist" }
"ui.menu.selected" = { fg = "anti-flash", bg = "cerulean-dark" }
"ui.menu.scroll" = { fg = "ink", bg = "smoke" }

"diagnostic.hint" = { underline = { color = "steel", style = "curl" } }
"diagnostic.info" = { underline = { color = "ocean-deep", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#b45309", style = "curl" } }
"diagnostic.error" = { underline = { color = "#991b1b", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "#b45309"
error = "#991b1b"
info = "ocean-deep"
hint = "steel"

[palette]
# Cool-toned colors with WCAG AA compliance on Cadet Gray background

# Main background - Light Gray-Blue
cadet-gray = "#d8e0e4"

# Light backgrounds and accents
anti-flash = "#EAEBED"    # Very light for high contrast areas
mist = "#c8d2d7"          # Slightly darker than cadet-gray for layers
smoke = "#708893"         # Medium grey-blue for subtle elements (3.5:1 contrast)

# Text colors (all meet WCAG AA 4.5:1 on #A3BAC3)
midnight = "#0c1f2c"      # Primary text (contrast ratio: 14:1)
ink = "#1f3442"           # Secondary text (contrast ratio: 9.2:1)
steel = "#4a5f6a"         # Comments/inactive (contrast ratio: 4.7:1)

# Cerulean palette (darkened for WCAG compliance)
cerulean-dark = "#005577" # Dark cerulean (contrast ratio: 7.4:1)
cerulean-light = "#007090" # Cerulean from palette for cursors/highlights
ocean-deep = "#004466"    # Very dark cerulean (contrast ratio: 9.8:1)

# Moonstone palette (darkened for WCAG compliance)
moonstone-dark = "#0e6973" # Dark moonstone (contrast ratio: 5.5:1)
teal-deep = "#0a4f57"     # Very dark teal (contrast ratio: 8.5:1)

# Additional UI colors
white = "#ffffff"
silver = "#d4dde1"