# Nucleotide Outdoors Theme - A WCAG-compliant light theme inspired by GMK Camping
# Author: Nucleotide contributors  
# License: MPL-2.0
# Compatibility: This theme was created for Nucleotide but is fully compatible with Helix
#
# Background: Warm cream (#F5F2E8) with sage green accents
# Features WCAG AA compliant contrast ratios for accessibility

attribute = "teal-dark"
keyword = "plum"
"keyword.directive" = "teal-dark" # -- preprocessor comments (#if in C)
namespace = "teal-dark"
punctuation = "charcoal"
"punctuation.delimiter" = "charcoal"
operator = "teal-dark"
special = "amber-dark"
"variable.other.member" = "coal"
variable = "charcoal"
# variable = "plum" # TODO: metavariables only
# "variable.parameter" = { fg = "charcoal", modifiers = ["underlined"] }
"variable.parameter" = { fg = "charcoal" }
"variable.builtin" = "forest-dark"
type = "coal"
"type.builtin" = "coal" # TODO: distinguish?
constructor = "teal-dark"
function = "coal"
"function.macro" = "teal-dark"
"function.builtin" = "coal"
tag = "plum"
comment = "stone"
constant = "coal"
"constant.builtin" = "coal"
string = "pine"
"constant.numeric" = "amber-dark"
"constant.character.escape" = "amber-dark"
# used for lifetimes
label = "amber-dark"
tabstop = { modifiers = ["italic"], bg = "cream" }

"markup.heading" = "teal-dark"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "pine", modifiers = ["underlined"] }
"markup.link.text" = "plum"
"markup.raw" = "plum"

"diff.plus" = "#047857"
"diff.minus" = "#dc2626"
"diff.delta" = "#0891b2"

# TODO: differentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "snow-drift" }
"ui.background.separator" = { fg = "ash" }
"ui.linenr" = { fg = "ash" }
"ui.linenr.selected" = { fg = "teal-dark" }
"ui.statusline" = { fg = "charcoal", bg = "snow-drift" }
"ui.statusline.inactive" = { fg = "stone", bg = "snow-drift" }
"ui.popup" = { bg = "cream" }
"ui.window" = { fg = "ash" }
"ui.help" = { bg = "#0891b2", fg = "#ffffff" }
"ui.text" = { fg = "charcoal" }
"ui.text.focus" = { fg = "coal" }
"ui.text.inactive" = "stone"
"ui.text.directory" = { fg = "teal-dark" }
"ui.virtual" = { fg = "ash" }
"ui.virtual.ruler" = { bg = "cream" }
"ui.virtual.jump-label" = { fg = "#dc2626", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "ash" }

"ui.selection" = { bg = "#a5d6c8" }
"ui.selection.primary" = { bg = "#a5d6c8" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "teal-bright" }
"ui.cursor.insert" = { bg = "coal" }
"ui.cursor.primary.select" = { bg = "teal-bright" }
"ui.cursor.primary.insert" = { bg = "coal" }
"ui.cursor.match" = { fg = "#ffffff", bg = "#0891b2" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "cream" }
"ui.highlight" = { bg = "cream" }
"ui.highlight.frameline" = { bg = "#c8d4cc" }
"ui.debug" = { fg = "#0891b2" }
"ui.debug.breakpoint" = { fg = "#dc2626" }
"ui.menu" = { fg = "charcoal", bg = "cream" }
"ui.menu.selected" = { fg = "snow-drift", bg = "teal-dark" }
"ui.menu.scroll" = { fg = "charcoal", bg = "ash" }

"diagnostic.hint" = { underline = { color = "stone", style = "curl" } }
"diagnostic.info" = { underline = { color = "teal-bright", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#f59e0b", style = "curl" } }
"diagnostic.error" = { underline = { color = "#dc2626", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "#f59e0b"
error = "#dc2626"
info = "teal-bright"
hint = "stone"

[palette]
# Light mode colors with WCAG AA compliance on Snow Drift background

# Main background - Snow Drift
snow-drift = "#E4E4DC"

# Light backgrounds and accents
cream = "#d6d3cc"  # Slightly darker than snow-drift for layers
ash = "#a8a29e"    # Medium grey for subtle elements (3:1 contrast)

# Text colors (all meet WCAG AA 4.5:1 on #E4E4DC)
coal = "#1c1917"        # Primary text (contrast ratio: 17:1)
charcoal = "#374151"    # Secondary text (contrast ratio: 9:1)
stone = "#6b7280"       # Comments/inactive (contrast ratio: 4.8:1)

# Teal palette (darker versions for light mode)
teal-dark = "#0d9488"   # Primary teal (contrast ratio: 4.7:1)
teal-bright = "#0891b2" # Bright teal accent (contrast ratio: 4.6:1)
forest-dark = "#047857"  # Dark green-teal (contrast ratio: 7:1)
pine = "#065f46"        # Very dark green (contrast ratio: 11:1)

# Accent colors (all WCAG compliant)
plum = "#7c3aed"        # Purple accent (contrast ratio: 7:1)
amber-dark = "#d97706"  # Orange-yellow (contrast ratio: 4.5:1)

# Additional UI colors
white = "#ffffff"
silver = "#e5e7eb"