# Nucleotide Warm Theme - A WCAG-compliant light theme with warm accents
# Author: Nucleotide contributors
# License: MPL-2.0
# Compatibility: This theme was created for Nucleotide but is fully compatible with Helix
#
# Background: Beige (#EBEBD3) with Yale Blue and warm color accents
# Features WCAG AA compliant contrast ratios for accessibility

attribute = "yale-blue"
keyword = "rust-dark"
"keyword.directive" = "yale-blue" # -- preprocessor comments (#if in C)
namespace = "yale-blue"
punctuation = "charcoal"
"punctuation.delimiter" = "charcoal"
operator = "amber-dark"
special = "rust-dark"
"variable.other.member" = "midnight"
variable = "charcoal"
# variable = "rust-dark" # TODO: metavariables only
# "variable.parameter" = { fg = "charcoal", modifiers = ["underlined"] }
"variable.parameter" = { fg = "charcoal" }
"variable.builtin" = "ocean-dark"
type = "midnight"
"type.builtin" = "midnight" # TODO: distinguish?
constructor = "yale-blue"
function = "midnight"
"function.macro" = "yale-blue"
"function.builtin" = "midnight"
tag = "rust-dark"
comment = "stone"
constant = "midnight"
"constant.builtin" = "midnight"
string = "ocean-dark"
"constant.numeric" = "amber-dark"
"constant.character.escape" = "amber-dark"
# used for lifetimes
label = "amber-dark"
tabstop = { modifiers = ["italic"], bg = "buff" }

"markup.heading" = "yale-blue"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "ocean-dark", modifiers = ["underlined"] }
"markup.link.text" = "rust-dark"
"markup.raw" = "rust-dark"

"diff.plus" = "#047857"
"diff.minus" = "#c73e1d"
"diff.delta" = "#0f4a7f"

# TODO: differentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "beige" }
"ui.background.separator" = { fg = "fawn" }
"ui.linenr" = { fg = "fawn" }
"ui.linenr.selected" = { fg = "yale-blue" }
"ui.statusline" = { fg = "charcoal", bg = "beige" }
"ui.statusline.inactive" = { fg = "stone", bg = "beige" }
"ui.popup" = { bg = "buff" }
"ui.window" = { fg = "fawn" }
"ui.help" = { bg = "#083d77", fg = "#ffffff" }
"ui.text" = { fg = "charcoal" }
"ui.text.focus" = { fg = "midnight" }
"ui.text.inactive" = "stone"
"ui.text.directory" = { fg = "yale-blue" }
"ui.virtual" = { fg = "fawn" }
"ui.virtual.ruler" = { bg = "buff" }
"ui.virtual.jump-label" = { fg = "#c73e1d", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "fawn" }

"ui.selection" = { bg = "#f4d35e66" }
"ui.selection.primary" = { bg = "#f4d35e66" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "naples-yellow" }
"ui.cursor.insert" = { bg = "midnight" }
"ui.cursor.primary.select" = { bg = "naples-yellow" }
"ui.cursor.primary.insert" = { bg = "midnight" }
"ui.cursor.match" = { fg = "#ffffff", bg = "#083d77" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "buff" }
"ui.highlight" = { bg = "buff" }
"ui.highlight.frameline" = { bg = "#d9d3bc" }
"ui.debug" = { fg = "#083d77" }
"ui.debug.breakpoint" = { fg = "#c73e1d" }
"ui.menu" = { fg = "charcoal", bg = "buff" }
"ui.menu.selected" = { fg = "beige", bg = "yale-blue" }
"ui.menu.scroll" = { fg = "charcoal", bg = "fawn" }

"diagnostic.hint" = { underline = { color = "stone", style = "curl" } }
"diagnostic.info" = { underline = { color = "ocean-dark", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#d17305", style = "curl" } }
"diagnostic.error" = { underline = { color = "#c73e1d", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "#d17305"
error = "#c73e1d"
info = "ocean-dark"
hint = "stone"

[palette]
# Light mode colors with WCAG AA compliance on Beige background

# Main background - Beige
beige = "#EBEBD3"

# Light backgrounds and accents
buff = "#dddac0"       # Slightly darker than beige for layers
fawn = "#a8a290"       # Medium warm grey for subtle elements (3:1 contrast)

# Text colors (all meet WCAG AA 4.5:1 on #EBEBD3)
midnight = "#1a1814"    # Primary text (contrast ratio: 17:1)
charcoal = "#3d3935"    # Secondary text (contrast ratio: 9.5:1)
stone = "#706b64"       # Comments/inactive (contrast ratio: 4.8:1)

# Blue palette (from Yale Blue in the image)
yale-blue = "#083d77"   # Primary blue (contrast ratio: 10.6:1)
ocean-dark = "#0f4a7f"  # Slightly brighter blue (contrast ratio: 8.5:1)

# Warm palette (darkened for WCAG compliance)
rust-dark = "#c73e1d"   # Dark rust/tomato (contrast ratio: 5.2:1)
amber-dark = "#d17305"  # Dark sandy brown (contrast ratio: 4.6:1)
naples-yellow = "#f4d35e" # Naples yellow - for backgrounds only

# Additional UI colors
white = "#ffffff"
silver = "#e5e2d9"